feat: create healthchecks
openfoodfacts/search-a-licious pull request #133
Opened 2024-06-05 15:11 UTC by Marc-AntoineA

### What
* feat: create a new api route `/health` which return in json the status of the different services

### Fixes bug(s)
- Fixes #67

2024-06-06 07:57 UTC, alexgarel requested changes
Cool to have used the health library, it's clean.

Some changes required.

2024-06-06 07:57 UTC, alexgarel commented on app/api.py
> +    }
We want status to be the http status of the response.

Either you build an HttpResponse from those elements, either you raise HttpException with message as body if status is not 200, or return message (as json).

2024-06-06 07:57 UTC, alexgarel commented on app/health.py
> +    return False, "elasticvue connection check failed!"
Don't test it, elasticvue is a tool, it should have it's own monitoring if needed. It's not needed for the app to run.

2024-06-06 07:57 UTC, alexgarel commented on frontend/Dockerfile
> +  fonts-tlwg-loma-otf fonts-freefont-ttf
It's already in another PR :-)

2024-06-06 10:53 UTC, Marc-AntoineA commented on app/api.py
> +    }
Can you have a look to the new version?

2024-06-06 12:10 UTC, alexgarel requested changes
Sorry it may feel a bit picky, but I think it's better to avoid this double encoding / decoding.

2024-06-06 12:10 UTC, alexgarel commented on app/api.py
> +    return orjson.loads(message)
You can avoid decoding then encoding json, by simply passing success_handler=None to Healthcheck, it will return `message, success_status, success_headers` 

Same for failed_handler.

See https://github.com/ateliedocodigo/py-healthcheck/blob/develop/healthcheck/healthcheck.py#L115

2024-06-07 09:37 UTC, Marc-AntoineA commented on app/api.py
> +    return orjson.loads(message)
If we pass `success_handler=None`, message is only `OK` or `NOT OK` which is probably not enough info?

2024-06-07 12:31 UTC, alexgarel approved these changes
Go !

2024-06-07 12:32 UTC, merged