feat: be able to create scatter plots
openfoodfacts/search-a-licious pull request #189
Opened 2024-06-25 18:43 UTC by Marc-AntoineA

### What
Enrich the API to not only display bar charts but also scatter plots.

### Screenshot
![image](https://github.com/openfoodfacts/search-a-licious/assets/27521221/4eb1d7e9-718c-4a94-ac08-3f4767088518)

2024-06-28 08:10 UTC, alexgarel requested changes
@Marc-AntoineA I made some comments.

Also an important thing to change: add comments, at least to every class and to big blocks of codes. At least a summary of what you are doing. (and for classes the big picture).

2024-06-28 08:10 UTC, alexgarel commented on app/api.py
> -    charts: GetSearchParamsTypes.charts = None,
I was thinking it was good to keep your field_name,x:y pattern here (and transform it inside the method), it offers a simple interface for simple use cases.

2024-06-28 08:10 UTC, alexgarel commented on frontend/src/search-chart.ts
>    override handleResults(event: SearchResultEvent) {
why isn't that in the mixin ? It seems to be the same for both charts.

2024-06-28 08:10 UTC, alexgarel commented on frontend/src/mixins/search-ctl.ts
> +        // @ts-ignore
I would prefer that we specify the ts rule we ignore. Also to make sense of what we need to ignore.

2024-06-28 08:11 UTC, alexgarel commented on frontend/src/mixins/search-ctl.ts
> +        // @ts-ignore
This also applies to the other `// @ts-ignore`.

Thanks in advance :-)

2024-06-28 09:50 UTC, Marc-AntoineA commented on app/_types.py
> +        # TODO check for x and y fields?
In fact some fields are not numeric but they are subfields of objects fields. Ex. `nutriments.fiber_100g` :/

2024-06-28 14:55 UTC, Marc-AntoineA commented on app/api.py
> -    charts: GetSearchParamsTypes.charts = None,
Done.

2024-06-28 14:56 UTC, Marc-AntoineA commented on app/charts.py
> +def build_scatter_chart(chart_option: ScatterChartType, search_result):
Oh yes, it’s only for the current page. Nice spot.

2024-06-28 14:58 UTC, Marc-AntoineA commented on app/charts.py
> +                    "fill": {"value": "transparent"},
If you want, it was the default value from the example.

2024-07-01 10:50 UTC, Marc-AntoineA commented on frontend/src/mixins/search-chart.ts
> +) => {
Changed to simple class with inheritance

2024-07-01 12:27 UTC, Marc-AntoineA commented on app/_types.py
> +        # TODO check for x and y fields?
Checked.

2024-07-01 12:29 UTC, Marc-AntoineA commented on frontend/src/mixins/search-ctl.ts
> +        // @ts-ignore
Removed

2024-07-04 13:28 UTC, alexgarel approved these changes
@Marc-AntoineA this is almost ok ! (just one mandatory thing to fix: the typing in search_get).

Thanks for this PR.

2024-07-04 13:28 UTC, alexgarel commented on app/validations.py
> +    check that x is a n object field
```suggestion
    check that x is an object field
```

2024-07-08 15:14 UTC, merged