feat: enhanced completion
openfoodfacts/search-a-licious pull request #259
Opened 2024-10-25 08:28 UTC by alexgarel

Improvements on taxonomies completion API:

* add the option of a preprocessor for taxonomies
* add a preprocessor for Open Food Facts to handle:
  * brands taxonomy
  * add main language
  * add xx entries to all languages
* fix to have names in synonyms
* add a score to completion to first match shortest entries
* enable querying multiple languages at once
* added tests

2024-10-30 08:58 UTC, stephanegigandet commented on app/query.py
> +    :param langs: the language we want search in
```suggestion
    :param langs: the languages we want search in
```

2024-10-30 09:10 UTC, alexgarel commented on frontend/src/search-suggester.ts
Add this component to documentation (and maybe tutorial ?)

2024-11-06 09:06 UTC, raphael0202 commented
In the search bar, when typing a single letter and deleting it, an autocomplete query with an empty `q` to the server:

http://search.localhost:8000/autocomplete?q=&langs=en&taxonomy_names=brands,categories&size=5

2024-11-06 09:37 UTC, raphael0202 commented
In `en` language, when searching `chicken`, I have the following results:

![Capture d’écran du 2024-11-06 10-34-32](https://github.com/user-attachments/assets/5f54a2ef-2919-4e3f-8e99-e1a94d5bd283)

I was expecting `Chickens` as first result instead of `chicken meat` (both terms are linked to the same taxonomy entry `en:chickens`).

Also, the search results are not normalized: some are capitalized, some are not.

2024-11-06 09:41 UTC, raphael0202 commented
Clicking on a brand suggested by auto-completion does not seem to work. For example, with `Casino`, we have 0 results when clicking on autosuggestion, while clicking on `casino` on the left brand panel returns 4.3k results.
It looks like it's due to wrong language prefix added when clicking on autosuggestion:

http://search.localhost:8000/static/off.html?off_q=&off_facetsFilters=brands%3A%22en%3Acasino%22&off_page=1

2024-11-06 09:51 UTC, raphael0202 requested changes
It looks good to me, I added a few remarks about possible bugs above!

2024-11-06 15:30 UTC, alexgarel commented
> Clicking on a brand suggested by auto-completion does not seem to work. For example, with Casino, we have 0 results when clicking on autosuggestion, while clicking on casino on the left brand panel returns 4.3k results.
> It looks like it's due to wrong language prefix added when clicking on autosuggestion

The prefix is not wrong in regard to the taxonomy… but the brands_tags field is different from the rest of the _tags field because it has no language prefix…

I will remove the language prefix for now.

2024-11-06 18:33 UTC, alexgarel commented
> In en language, when searching chicken, I have the following results:
> I was expecting Chickens as first result instead of chicken meat (both terms are linked to the same taxonomy entry en:chickens).

> Also, the search results are not normalized: some are capitalized, some are not.

I tried to change entries order in the array, but it does not change… and don't know how to change that in Elasticsearch…

So I added the entry name in the label, this way it's more easy to understand.

2024-11-06 18:55 UTC, teolemon commented
We could get a category image using wikidata: https://wikidata.org/w/rest.php/wikibase/v1/entities/items/Q20034?_fields=type,labels,descriptions,aliases,statements,sitelinks (image is P18)

2024-11-07 08:06 UTC, raphael0202 approved these changes

2024-11-12 08:34 UTC, merged