Autocomplete
openfoodfacts/search-a-licious pull request #60
Opened 2023-10-19 13:59 UTC by frankbaele

### What
- added taxonomy autocomplete

2023-10-26 10:08 UTC, raphael0202 requested changes
Thank you for your PR :)
I've added a couple of comments

2023-10-26 10:08 UTC, raphael0202 commented on app/openfoodfacts.py
> +                        lang_codes := country_node.properties.get("language_codes", {}).get(
is it due to black linter? because I have black linting configured as well, there shouldn't be any differences

2023-10-26 10:08 UTC, raphael0202 commented on app/openfoodfacts.py
> +class CompletionProcessor(BaseResultProcessor):
It shouldn't be in "openfoodfacts" module, as we only have classes related to Open Food Facts there. You should probably move it to `app.postprocessing`

2023-10-26 10:08 UTC, raphael0202 commented on app/indexing.py
> +            if field.type == FieldType.text_lang_completion:
You need an `elif` there to be consistent with the other conditions

2023-10-26 10:08 UTC, raphael0202 commented on app/indexing.py
> +                field_input = process_text_lang_field(
Open Food Facts taxonomies are not in the same format as "text_lang" fields, each language has a different subfield. Shouldn't you create a new function to process these fields?

2023-10-26 10:08 UTC, raphael0202 commented on app/indexing.py
> +                    split=field.split,
We shouldn't have split, lang_separator, split_separator parameters here

2023-10-26 10:08 UTC, raphael0202 commented on data/config/taxonomy.yml
> +index:
I think it's a better idea to keep one single configuration file per project, and not having separate config for taxonomies. Can you use the `taxonomy_config` part of the config file to set-up configuration about taxonomy indices and autocomplete?

2023-11-08 07:30 UTC, frankbaele commented on app/query.py
> +    query = query.suggest('labels', q, completion={'field': f"labels.{lang}", 'size':size})
ok

2023-11-08 07:30 UTC, frankbaele commented on app/query.py
> +    :param lang: the languages we want to support
ok

2023-11-08 08:10 UTC, frankbaele commented on app/openfoodfacts.py
> +        for field in response.suggest:
suggest is not a regular dict but a AttrDict so it doesn't have items()

2023-11-08 08:12 UTC, frankbaele commented on app/openfoodfacts.py
> +class CompletionProcessor(BaseResultProcessor):
fixed

2023-11-08 08:15 UTC, frankbaele commented on app/indexing.py
> +            if field.type == FieldType.text_lang_completion:
correct!

2023-11-08 13:11 UTC, frankbaele commented on app/indexing.py
> +                    split=field.split,
wrote a sperate processor for nested lang source fields

2023-11-08 13:12 UTC, frankbaele commented on app/indexing.py
> +                field_input = process_text_lang_field(
wrote a seperate processor for the nested lang fields

2023-11-09 09:53 UTC, merged

2023-11-09 10:02 UTC, alexgarel commented
Thank you so much @frankbaele for your contribution !